@startuml
!include ../l4/l4_4.pu
!include ../l4/l4_27.pu

package "中機能"{
  package "自動アノテーション機能"{
    object "中機能" as 3_3 #Red{
      id = 3-3
      detail = アノテーション結果を画像一覧で表示する
    }
  }
}

3_3 <-- 4_4
3_3 <-- 4_27
@enduml