@startuml
!include ../l4/l4_8.pu
!include ../l4/l4_9.pu

package "中機能"{
  package "画像ビュワー"{
    object "中機能" as 3_9 #Red{
      id = 3-9
      detail = ディレクトリ表示モード
    }
  }
}

3_9 <-- 4_8
3_9 <-- 4_9
@enduml