@startuml
!include ../l2/l2_1.pu
!include ../l2/l2_2.pu
!include ../l2/l2_3.pu
!include ../l2/l2_4.pu
!include ../l2/l2_8.pu

package "目的"{
  object "目的" as 1_1 #Red{
    id = 1-1
    detail = GUIで画像認識モデル作成に向けた画像アノテーションを自動化
  }
}

1_1 <-- 2_1
1_1 <-- 2_2
1_1 <-- 2_3
1_1 <-- 2_4
1_1 <-- 2_8
@enduml