@startuml
!include ../l5/l5_9.pu
!include ../l5/l5_20.pu

package "小機能"{
  package "GUI"{
    object "小機能" as 4_8 #LightGreen{
      id = 4-8
      detail = ディレクトリパス階層でフィルタして表示できる
    }
  }
}

4_8 <-- 5_9
4_8 <-- 5_20
@enduml