@startuml
!include ../l5/l5_1.pu
!include ../l5/l5_9.pu

package "小機能"{
  package "GUI"{
    object "小機能" as 4_9{
      id = 4-9
      detail = ディレクトリパス階層でソートして表示できる
    }
  }
}

4_9 <-- 5_1
4_9 <-- 5_9
@enduml