@startuml
!include ./l3.pu

package "大機能" as l2{
  object "大機能" as 2_1 #Red{
    id = 2-1
    detail = 画像の自動アノテーション機能
  }

  object "大機能" as 2_2 #Red{
    id = 2-2
    detail = 自動アノテーションした結果を閲覧できる機能
  }

  object "大機能" as 2_3{
    id = 2-3
    detail = アノテーション結果から領域を調整できる機能
  }

  object "大機能" as 2_4{
    id = 2-4
    detail = 選択したアノテーション結果をエクスポートできる機能
  }

  object "大機能" as 2_5 #LightGreen{
    id = 2-5
    detail = フォルダ内を再帰的に検索して画像を表示
  }

  object "大機能" as 2_6 #LightGreen{
    id = 2-6
    detail = フォルダ内の画像を一覧で表示できる
  }

  object "大機能" as 2_7 #LightGreen{
    id = 2-7
    detail = フォルダ内の画像をビュワーで確認できる
  }
}

2_1 <-- 3_2
2_1 <-- 3_4
2_1 <-- 3_5
2_2 <-- 3_1
2_2 <-- 3_3
2_3 <-- 3_6
2_4 <-- 3_2
2_5 <-- 3_4
2_5 <-- 3_7
2_5 <-- 3_8
2_5 <-- 3_9
2_6 <-- 3_8
2_6 <-- 3_9
2_7 <-- 3_11
@enduml