@startuml
!include ./l4.pu

package "中機能"{
  object "中機能" as 3_1 #red{
    id = 3-1
    detail = アノテーション結果をマークした画像を表示する機能
  }

  object "中機能" as 3_2 #Red{
    id = 3-2
    detail = アノテーション結果は実行ごとにプロジェクトとして保存する
  }

  object "中機能" as 3_3 #Red{
    id = 3-3
    detail = アノテーション結果を画像一覧で表示する
  }

  object "中機能" as 3_4 #LightGreen{
    id = 3-4
    detail = 対象をフォルダ選択して指定できる
  }

  object "中機能" as 3_5 #LightGreen{
    id = 3-5
    detail = 使用する画像認識モデル選択して指定できる
  }

  object "中機能" as 3_6{
    id = 3-6
    detail = GUIで画像の上に表示した領域（枠）を調整できる
  }

  object "中機能" as 3_7 #LightGreen{
    id = 3-7
    detail = フォルダ内を再帰的に検索できる
  }

  object "中機能" as 3_8 #LightGreen{
    id = 3-8
    detail = 全画像表示モード
  }

  object "中機能" as 3_9 #LightGreen{
    id = 3-9
    detail = ディレクトリ表示モード
  }

  object "中機能" as 3_10 #LightGreen{
    id = 3-10
    detail = 画像一覧の表示サイズを変更できる
  }

  object "中機能" as 3_11 #LightGreen{
    id = 3-11
    detail = 画像ビュワーの画像表示サイズを変更できる
  }
}

3_1 <-- 4_1
3_1 <-- 4_2
3_1 <-- 4_4
3_2 <-- 4_3
3_3 <-- 4_2
3_3 <-- 4_4
3_4 <-- 4_3
3_5 <-- 4_3
3_6 <-- 4_5
3_7 <-- 4_3
3_8 <-- 4_2
3_8 <-- 4_6
3_8 <-- 4_7
3_9 <-- 4_2
3_9 <-- 4_8
3_9 <-- 4_9
3_10 <-- 4_10
3_11 <-- 4_10
@enduml