@startuml
package "構成"{
  object "構成" as 5_1 #LightGreen{
    id = 5-1
    detail = GUIをelectronで実装する
  }

  object "構成" as 5_2 #LightGreen{
    id = 5-2
    detail = 画像認識モデルはyoloを使用する
  }

  object "構成" as 5_3 #LightGreen{
    id = 5-3
    detail = nodejsを使用する
  }

  object "構成" as 5_4 #LightGreen{
    id = 5-4
    detail = pythonを使用する
  }

  object "構成" as 5_5 #LightGreen{
    id = 5-5
    detail = 画像処理はopencvを使用する
  }

  object "構成" as 5_6{
    id = 5-6
    detail = GUI上で画像編集操作できるように(T.B.D)を使用する
  }

  object "構成" as 5_7{
    id = 5-7
    detail = GUIに画像を表示する
  }
}

5_1 <-- 5_3
5_2 <-- 5_4
5_5 <-- 5_4
5_6 <-- 5_3
5_7 <-- 5_1
@enduml