@startuml
!include ../l3/l3_11.pu
!include ../l3/l3_12.pu
!include ../l3/l3_13.pu
!include ../l3/l3_14.pu
!include ../l3/l3_15.pu
!include ../l3/l3_16.pu
!include ../l3/l3_17.pu
!include ../l3/l3_18.pu
!include ../l3/l3_19.pu
!include ../l3/l3_20.pu

package "大機能" as l2{
  package "画像ビュワー"{
    object "大機能" as 2_7 #LightGreen{
      id = 2-7
      detail = フォルダ内の画像をビュワーで確認できる
    }
  }
}

2_7 <-- 3_11
2_7 <-- 3_12
2_7 <-- 3_13
2_7 <-- 3_14
2_7 <-- 3_15
2_7 <-- 3_16
2_7 <-- 3_17
2_7 <-- 3_18
2_7 <-- 3_19
2_7 <-- 3_20
@enduml