@startuml
!include ../l3/l3_24.pu
!include ../l3/l3_25.pu
!include ../l3/l3_27.pu

package "大機能" as l2{
  package "GUI全般"{
    object "大機能" as 2_8 #LightGreen{
      id = 2-8
      detail = GUIは既存のウィンドウを使用せず、カスタムされたウィンドウを表示できる
    }
  }
}

2_8 <-- 3_24
2_8 <-- 3_25
2_8 <-- 3_27
@enduml